pom.xml
tck/pom.xml
tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TestClassAnnotation.java
tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TestMethodAnnotations.java

Signed-off-by: Heiko W. Rupp <hrupp@redhat.com>

Get the repository to compile.

---

spec/src/main/asciidoc/microprofile-opentracing-spec.asciidoc

* use term `SpanContext` for inject/extract
* define when tag `span.kind` should be used

Use term SpanContext for inject/extract, explain span.kind tag

---

spec/src/main/asciidoc/license-alv2.asciidoc
spec/src/main/asciidoc/microprofile-opentracing-spec.asciidoc

Signed-off-by: Heiko W. Rupp <hrupp@redhat.com>
@Steve-Fontes @pavolloffay

Text changes to the Spec, also try to have 1 sentence per line.

---

spec/src/main/asciidoc/microprofile-opentracing-spec.asciidoc

Specify when error tag is used on server side

---

spec/src/main/asciidoc/microprofile-opentracing-spec.asciidoc

Method @Traced annotation takes precedence

---

spec/src/main/asciidoc/microprofile-opentracing-spec.asciidoc

@Steve-Fontes could you please review?

Clarify that errors should be logged

---

tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpentracingClientTests.java

Remove typo from code

---

spec/src/main/asciidoc/microprofile-opentracing-spec.asciidoc
tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpentracingClientTests.java
tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TestServerWebServices.java
tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TestWebServicesApplication.java
tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TracerWebService.java
tck/src/main/java/org/eclipse/microprofile/opentracing/tck/tracer/ConsumableTree.java
tck/src/main/java/org/eclipse/microprofile/opentracing/tck/tracer/TestSpan.java
tck/src/main/java/org/eclipse/microprofile/opentracing/tck/tracer/TestSpanTree.java

TCK: Multi-threaded test, nested span breadth option, test HTTP 500 error, and test log entries

---

spec/src/main/asciidoc/microprofile-opentracing-spec.asciidoc

Updates from Nov 30 discussion

---

tck/pom.xml
tck/running_the_tck.asciidoc
tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpentracingClientTests.java

Signed-off-by: Kevin Grigorenko <kevin.grigorenko@us.ibm.com>

Simplify instructions on running the TCK and add resteasy dependencies.

---

tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TestServerWebServices.java
tck/src/main/java/org/eclipse/microprofile/opentracing/tck/tracer/TestSpan.java

Fix javadoc so verification passes and RC build can progress

fixes for build break

---

spec/src/main/asciidoc/microprofile-opentracing.asciidoc

For https://github.com/eclipse/microprofile-opentracing/issues/47

Clarify OpenCensus text

---

pom.xml

Add sonatype plugin to pom

---

pom.xml

Moved sonatype plugin to correct place in pom file

fix sonatype plugin in pom

---

api/pom.xml
pom.xml

Use osgi version dependency in package-info.java rather than @Version

Apipom dependency

---

tck/pom.xml
tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpentracingClientTests.java
tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TestServerWebServices.java
tck/src/main/java/org/eclipse/microprofile/opentracing/tck/tracer/TestSpan.java
tck/src/main/java/org/eclipse/microprofile/opentracing/tck/tracer/TestTracer.java

Bump OpenTracing version to 0.31.0

---

tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpentracingClientTests.java

Resolves #66 
@kgibm could you please review?

Fix radom id collision

---

spec/src/main/asciidoc/microprofile-opentracing.asciidoc

This PR is for issue #77
Signed-off-by: Doychin Bondzhev <doychin@dsoft-bg.com>

Fix package name for JAX-RS Client class

---

spec/src/main/asciidoc/changelog.asciidoc
spec/src/main/asciidoc/microprofile-opentracing.asciidoc

Add changelog to spec

---

README.adoc

Polish root readme

---

tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingBaseTests.java

Fix javadoc

---

tck/pom.xml

Make CDI provided

---

spec/src/main/asciidoc/microprofile-opentracing.asciidoc
tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingBaseTests.java
tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingClientBaseTests.java
tck/src/main/java/org/eclipse/microprofile/opentracing/tck/tracer/TestSpan.java

Log exceptions thrown by explicit instrumentation

---

spec/src/main/asciidoc/configuration.asciidoc
spec/src/main/asciidoc/microprofile-opentracing.asciidoc

Introduce configuration section

---

spec/src/main/asciidoc/changelog.asciidoc

Update changelog for 1.2

---

spec/src/main/asciidoc/changelog.asciidoc

Fix typo in changelog antiject

---

spec/pom.xml

Add number to spec name

---

tck/running_the_tck.asciidoc
tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingClassMethodNameClientTests.java
tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingDefaultClientTests.java

Rename class to match OpenTracing

---

README.adoc
api/pom.xml
pom.xml
spec/pom.xml
tck/pom.xml

Fix and update metadata in pom

---

tck/src/main/java/org/eclipse/microprofile/opentracing/tck/ClientRegistrarTests.java
tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TestClientRegistrarWebServices.java
tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TestWebServicesApplication.java

Just additional tests which fully cover client registrar.

Test client registrar

---

spec/src/main/asciidoc/microprofile-opentracing.asciidoc

Fix typo in spec

---

spec/src/main/asciidoc/microprofile-opentracing.asciidoc
tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingHTTPPathNameTests.java
tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/WildcardClassService.java

Resolves #123 
@fmhwong could you please have a look?

Clarify wildcard path with regular expressions

---

pom.xml

Bump rest client to 1.2-RC1

---

pom.xml

@fmhwong could you please review?

Bump rest-client to 1.2 final

---

spec/src/main/asciidoc/changelog.asciidoc

Add changelog for 1.3.1

---

pom.xml

Fixes Jenkinf failures https://ci.eclipse.org/microprofile/job/MicroProfile%20Releases/309/console, search for `https://ci.eclipse.org/microprofile/job/MicroProfile%20Releases/309/console`
Inspired by https://github.com/eclipse/microprofile-rest-client/commit/f82d7914a63a1a1fa63d8ec4e5bdb6ba9e6fc9b8

Fix gpg signing failures

---

pom.xml

Closes #173 
Signed-off-by: Emily Jiang <emijiang6@googlemail.com>

Enable compile using Java11

---

pom.xml
tck/pom.xml

Bump arquillian to 1.6.0

---

api/pom.xml

Closes #171 
Signed-off-by: Emily Jiang <emijiang6@googlemail.com>

Add bnd baseline plugin for versioning packages

---

pom.xml
spec/pom.xml
spec/src/main/asciidoc/changelog.asciidoc
spec/src/main/asciidoc/microprofile-opentracing.asciidoc
tck/base/pom.xml
tck/base/src/main/java/org/eclipse/microprofile/opentracing/tck/tracer/TestSpan.java
tck/base/src/main/java/org/eclipse/microprofile/opentracing/tck/tracer/TestTracer.java

Bump OpenTracing API to 0.33.0

---

api/pom.xml

Make OSGI dependency provided

---

pom.xml

Upgrade MP Rest Client to 2.0-RC2

---

spec/src/main/asciidoc/changelog.asciidoc

Related to #191 
@fmhwong could you please review?

Add changelog for 2.0

---

pom.xml

I messed up the history on the other branch.
Fixes #156 
Signed-off-by: Miguel Serra <Miguel.Serra@criticaltechworks.com>

Exclude transitive dependency on javax.el-api

---

spec/src/main/asciidoc/changelog.asciidoc

Add exclude transitive dependency on el to changelog

---

spec/src/main/asciidoc/changelog.asciidoc

Resolves #198 
@Emily-Jiang could you please review?

Split changelog sections

---

api/pom.xml

Signed-off-by: Emily Jiang <emijiang6@googlemail.com>

Use the last final release as the baseline

---

pom.xml

Update MicroProfile Config dependency to 2.0-RC1

Update MicroProfile Config dependency to 2.0-RC1

---

pom.xml

Update config to 2.0

---

pom.xml

Signed-off-by: xstefank <xstefank122@gmail.com>

Update MP REST client to 2.0

---

pom.xml

Signed-off-by: xstefank <xstefank122@gmail.com>

Add stagingProgressTimeoutMinutes parameter for the nexus plugin

---

CONTRIBUTING.adoc

Signed-off-by: xstefank <xstefank122@gmail.com>

Add CONTRIBUTING.adoc

---

spec/src/main/asciidoc/microprofile-opentracing.asciidoc

Make functionality of @Traced more clear

---

.gitignore
pom.xml

Due the github repo move. We need to update the url accordingly.

Update the url
