- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpentracingClientTests.java
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TestServerWebServices.java
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/tracer/TestSpan.java
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/tracer/TestSpanTree.java
Also added debug capabilities to Arquillian client and make debugging easier by clearing the tracer before each test.
Signed-off-by: Kevin Grigorenko <kevin.grigorenko@us.ibm.com>
> Assert equality of span tags. Fixed two tests to check top-level tags.

- spec/src/main/asciidoc/microprofile-opentracing.asciidoc
Mostly minor typography fixes and some paragraph simplifications.
- use OpenTracing, OpenCensus
- comply with OpenTracing semantic conventions
- fix links
- move span extraction section to inbound requests
- use code style where it makes sense
> Improve typography, Use OpenTracing

- spec/pom.xml
Here's the change we need in the spec pom.xml for proper html generation.  I have also created this 1.0-branch which we will keep around.  I have manually updated the artifacts for the 1.0 Release tag to include the Final 1.0 spec pdf and html.  This change should resolve both issue #60 and issue #59.
I propose that we take the educated risk that the eclipse repository for the spec html document either won't be accessed or it won't be noticed that the version is incorrect.  The content is still 1.0 and is accurate.  It's just the version tag that is incorrect.  We should be able to live with that until we do the next 1.x or 2.x release of opentracing.
> update spec pom.xml for proper html generation

- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TestServerWebServices.java
* This span is manually passed around, therefore scope is
not necessary and creates a leak.
* Also use .start instead of deprecated startManual
> Do not use activeSpan/scope for manually passed span

- api/src/main/java/org/eclipse/microprofile/opentracing/ClientTracingRegistrar.java
- api/src/main/java/org/eclipse/microprofile/opentracing/ClientTracingRegistrarProvider.java
- spec/src/main/asciidoc/microprofile-opentracing.asciidoc
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpentracingClientTests.java
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TestServerWebServices.java
Resolves #14 
This does not require client tracing globally enabled. Whether it's client tracing globally enabled is optional - depends on the implementation. Client tracing can be explicitly enabled by `client = ClientTracingRegistrar.configure(builder)` , when it's globally enabled it's noop.
It's WIP: it needs more documentation work.
> Explicitly enable tracing for clients

- pom.xml
- spec/src/main/asciidoc/microprofile-opentracing.asciidoc
- tck/pom.xml
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingBaseTests.java
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingClientTests.java
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingSkipPatternTests.java
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpentracingClientTests.java
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TestServerSkipAllWebServices.java
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TestServerWebServices.java
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TestWebServicesApplication.java
- tck/src/main/resources/META-INF/microprofile-config.properties
Resolves: #16 
Example implementation: https://github.com/smallrye/smallrye-opentracing/pull/23. The implementation itself is in https://github.com/opentracing-contrib/java-jaxrs/blob/master/opentracing-jaxrs2/src/main/java/io/opentracing/contrib/jaxrs2/server/ServerTracingFilter.java#L128
> Add support for skip pattern

- api/pom.xml
- pom.xml
- tck/pom.xml
Remove unnecessary dependencies. Other MP projects do not depend on them.
> Remove geronimo and annotation API

- spec/src/main/asciidoc/microprofile-opentracing.asciidoc
- tck/pom.xml
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingBaseTests.java
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingSkipPatternTests.java
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/HealthServlet.java
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/MetricsServlet.java
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/OpenAPIServlet.java
> Use default skip pattern for MP metrics, openapi, health

- spec/src/main/asciidoc/microprofile-opentracing.asciidoc
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingHTTPPathNameTests.java
> Add HTTP method to http-path operation name

- spec/src/main/asciidoc/microprofile-opentracing.asciidoc
> Clarify default value when skip pattern is defined

- spec/src/main/asciidoc/microprofile-opentracing.asciidoc
@fmhwong could you please review?
> Escape asterik in spec

- .gitignore
Add `.DS_Store` to `.gitignore` so git doesn't show it as a untracked file on MacOS
> Ignore MacOS .DS_Store

- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingBaseTests.java
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingClientBaseTests.java
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingSkipPatternTests.java
Fixes #131 
1. Create a new assertEqualErrorTrees() to check for returnedTree which expects an error.
1. Switch testAnnotationException() to call assertEqualErrorTrees()
1. Fix the url for `/metrics/base`
> Do not fail test when additional data in the tree

- pom.xml
- spec/src/main/asciidoc/microprofile-opentracing.asciidoc
- tck/pom.xml
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingBaseTests.java
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingClientBaseTests.java
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingMpRestClientTests.java
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/ClientServices.java
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/ClientServicesTracingDisabled.java
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TestServerWebServices.java
Resolves #82 
The current proposed solution:
All clients are by default traced. Tracing could be disabled via `Traced(false)` on the client interface or method.
Issues to address:
SmallRye implementation https://github.com/smallrye/smallrye-opentracing/pull/28
Other links to blocking issues, mostly for testing (SmallRye): 
* https://github.com/smallrye/smallrye-rest-client/issues/11
* https://github.com/smallrye/smallrye-rest-client/issues/6
> Instrument mp-rest-client

- tck/base/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingBaseTests.java
- tck/base/src/main/java/org/eclipse/microprofile/opentracing/tck/application/ApplicationUtils.java
- tck/base/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TestAnnotatedClass.java
- tck/base/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TestServerWebServices.java
- tck/base/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TestWebServicesApplication.java
- tck/rest-client/src/main/java/org/eclipse/microprofile/opentracing/tck/rest/client/RestClientApplication.java
- tck/rest-client/src/main/java/org/eclipse/microprofile/opentracing/tck/rest/client/RestClientServices.java
Resolves #142 
The base jaxrs app is removed from deployment in rest-client module
therefore it cannot be referenced from other resource classes.
> Remove references from base jax-rs APP to avoid CNFE

- tck/rest-client/src/main/java/org/eclipse/microprofile/opentracing/tck/rest/client/ClientServices.java
- tck/rest-client/src/main/java/org/eclipse/microprofile/opentracing/tck/rest/client/ClientServicesTracingDisabled.java
Add return MINE type to interfaces.  Fixes #144
> Add return MINE type

- api/pom.xml
- pom.xml
- tck/base/pom.xml
- tck/base/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingBaseTests.java
- tck/base/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TestWebServicesApplication.java
- tck/rest-client/pom.xml
- tck/rest-client/src/main/java/org/eclipse/microprofile/opentracing/tck/rest/client/RestClientApplication.java
Resolves #161 
Resolves #159 
I have also taken the opportunity to remove the dependency on Jackson and use `jakarta.json.bind-api` instead.
> Use Jakarta APIs

- tck/base/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingBaseTests.java
Explicitly specify the Maven Central URL `https://repo.maven.apache.org/maven2/` to avoid using the default `http://repo.maven.apache.org/maven2/`
> Use HTTPS to download from Maven Central

- .gitignore
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpentracingClientTests.java
Related to #165
Explicitly specify the Maven Central URL https://repo.maven.apache.org/maven2/ to avoid using the default http://repo.maven.apache.org/maven2/
> [1.0-branch] Use HTTPS to download from Maven Central

- .gitignore
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpentracingClientTests.java
Related to #165
Explicitly specify the Maven Central URL https://repo.maven.apache.org/maven2/ to avoid using the default http://repo.maven.apache.org/maven2/
> [1.1-branch] Use HTTPS to download from Maven Central 

- tck/base/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingBaseTests.java
- tck/base/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TestWebServicesApplication.java
- tck/rest-client/src/main/java/org/eclipse/microprofile/opentracing/tck/rest/client/RestClientApplication.java
Remove `io.opentracing:opentracing-api:0.31.0` and `com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:2.9.0` from the WAR file.
Related-to: #175
> [1.3-branch] Remove opentracing-api and jackson in WAR

- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpentracingClientTests.java
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TestWebServicesApplication.java
Remove `io.opentracing:opentracing-api:0.30.0` and `com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:2.9.0` from the WAR file.
Related-to: #175
> [1.0-branch] Remove opentracing-api and jackson in WAR

- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpentracingClientTests.java
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TestWebServicesApplication.java
Remove `io.opentracing:opentracing-api:0.31.0` and `com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:2.9.0` from the WAR file.
Related-to: #175
> [1.1-branch] Remove opentracing-api and jackson in WAR

- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingBaseTests.java
- tck/src/main/java/org/eclipse/microprofile/opentracing/tck/application/TestWebServicesApplication.java
Remove `io.opentracing:opentracing-api:0.31.0` and `com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:2.9.0` from the WAR file.
Related-to: #175
> [1.2-branch] Remove opentracing-api and jackson in WAR

- tck/base/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingBaseTests.java
Remove `io.opentracing:opentracing-api:0.31.0` from the WAR file.
Fixes #175
> Remove opentracing-api in WAR

- api/pom.xml
- pom.xml
- spec/pom.xml
- tck/base/pom.xml
- tck/pom.xml
- tck/rest-client/pom.xml
It is somehow confusing that a branch for 1.3.x exits, but master is also 1.3.x. Plus, master was at 1.3.2-SNAPSHOT and 1.3.3 was already released.
> Update version to 2.0-SNAPSHOT

- pom.xml
Related to #191 
Bump MP-Config to 1.4. I assume Config 1.4 will be pulled into MP 4.0. Is that right @kenfinnigan or @Emily-Jiang?
> Bump MicroProfile-Config to 1.4

- pom.xml
- tck/base/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingClassMethodNameClientTests.java
- tck/base/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingHTTPPathNameTests.java
- tck/base/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingSkipPatternTests.java
Related to #194 
@Emily-Jiang could you please review?
> Bump MP-Config to 2.0-m1

- api/pom.xml
This PR fixes https://github.com/eclipse/microprofile-opentracing/pull/202
The build was still failing on https://ci.eclipse.org/microprofile/job/MicroProfile%20Releases/415/console
```
[INFO] [INFO] The baseline version was found to be 2.0-RC1
[INFO] [ERROR] The bundle version change (2.0.0 to 2.0.0) is too low, the new version must be at least 2.0.1
```
This is the correct configuration according to https://github.com/eclipse/microprofile-metrics/blob/master/api/pom.xml#L95
> Fix baseline maven plugin configuration

- spec/src/main/asciidoc/microprofile-opentracing.asciidoc
While reviewing the spec, I noticed the old URL responded with 404.
> Fixing broken URL to opentracing.io supported tracers.

- api/pom.xml
Update BND to 5.0.0 which is used by most other spec projects. The very old 2.4 version has an issue that breaks the build in our productization environment.
> Update BND plugin
